// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe7gNfS0eB1xbyAKiSrrqin8S2VcUz9Ls',
    appId: '1:619815305215:web:f497de7d87a3c1484bb1ca',
    messagingSenderId: '619815305215',
    projectId: 'cineluxe-3a451',
    authDomain: 'cineluxe-3a451.firebaseapp.com',
    storageBucket: 'cineluxe-3a451.firebasestorage.app',
    measurementId: 'G-1KBN8HMLPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuASnwLeM2xxiTSsk44KTOnWwkyttjq2E',
    appId: '1:619815305215:android:5a3e1d08279095b14bb1ca',
    messagingSenderId: '619815305215',
    projectId: 'cineluxe-3a451',
    storageBucket: 'cineluxe-3a451.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1JzVO-PgDsPV80oZrh6P7fu_bbuyKIRI',
    appId: '1:619815305215:ios:d8a825e2b5f4d7e34bb1ca',
    messagingSenderId: '619815305215',
    projectId: 'cineluxe-3a451',
    storageBucket: 'cineluxe-3a451.firebasestorage.app',
    iosBundleId: 'com.example.cineluxe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1JzVO-PgDsPV80oZrh6P7fu_bbuyKIRI',
    appId: '1:619815305215:ios:d8a825e2b5f4d7e34bb1ca',
    messagingSenderId: '619815305215',
    projectId: 'cineluxe-3a451',
    storageBucket: 'cineluxe-3a451.firebasestorage.app',
    iosBundleId: 'com.example.cineluxe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe7gNfS0eB1xbyAKiSrrqin8S2VcUz9Ls',
    appId: '1:619815305215:web:87c79722a82ff6bb4bb1ca',
    messagingSenderId: '619815305215',
    projectId: 'cineluxe-3a451',
    authDomain: 'cineluxe-3a451.firebaseapp.com',
    storageBucket: 'cineluxe-3a451.firebasestorage.app',
    measurementId: 'G-02S3X1MHT8',
  );
}
